/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    guests: Guest;
    'guest-messages': GuestMessage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    guests: GuestsSelect<false> | GuestsSelect<true>;
    'guest-messages': GuestMessagesSelect<false> | GuestMessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    personalization: Personalization;
    'new-guest-message': NewGuestMessage;
  };
  globalsSelect: {
    personalization: PersonalizationSelect<false> | PersonalizationSelect<true>;
    'new-guest-message': NewGuestMessageSelect<false> | NewGuestMessageSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guests".
 */
export interface Guest {
  id: string;
  name: string;
  email: string;
  guestsCount?: number | null;
  guestNames?:
    | {
        fullName?: string | null;
        id?: string | null;
      }[]
    | null;
  profilePicture?: (string | null) | Media;
  /**
   * Custom message for the invitation. If empty, uses the default message.
   */
  message?: string | null;
  status?: ('not_sent' | 'sent' | 'confirmed' | 'declined') | null;
  token?: string | null;
  code?: string | null;
  phoneNumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guest-messages".
 */
export interface GuestMessage {
  id: string;
  owner: string | Guest;
  message: string;
  media?: (string | null) | Media;
  style?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('draft' | 'published' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'guests';
        value: string | Guest;
      } | null)
    | ({
        relationTo: 'guest-messages';
        value: string | GuestMessage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guests_select".
 */
export interface GuestsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  guestsCount?: T;
  guestNames?:
    | T
    | {
        fullName?: T;
        id?: T;
      };
  profilePicture?: T;
  message?: T;
  status?: T;
  token?: T;
  code?: T;
  phoneNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guest-messages_select".
 */
export interface GuestMessagesSelect<T extends boolean = true> {
  owner?: T;
  message?: T;
  media?: T;
  style?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personalization".
 */
export interface Personalization {
  id: string;
  weddingDate: string;
  couple?: {
    groom?: string | null;
    bride?: string | null;
  };
  /**
   * Text appearing at the top of the invitation (e.g. "You are invited")
   */
  headerCopy?: string | null;
  /**
   * Welcome text or initial greetings.
   */
  greetings?: string | null;
  /**
   * E.g: "Monetary Gift", "Gift Registry", etc.
   */
  giftType?: string | null;
  dressCode?: {
    text?: string | null;
    femaleImage?: (string | null) | Media;
    maleImage?: (string | null) | Media;
  };
  ceremony?: {
    time?: string | null;
    placeName?: string | null;
    gpsCoordinates?: {
      latitude?: number | null;
      longitude?: number | null;
    };
    placePhoto?: (string | null) | Media;
    mapPhoto?: (string | null) | Media;
  };
  reception?: {
    time?: string | null;
    placeName?: string | null;
    gpsCoordinates?: {
      latitude?: number | null;
      longitude?: number | null;
    };
    placePhoto?: (string | null) | Media;
    mapPhoto?: (string | null) | Media;
  };
  carousel?:
    | {
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  qrLayout?: {
    backgroundImage?: (string | null) | Media;
    dotsType?: ('rounded' | 'dots' | 'classy' | 'classy-rounded' | 'square' | 'extra-rounded') | null;
    color?: string | null;
    cornersSquareType?: ('dot' | 'square' | 'extra-rounded') | null;
    cornersSquareColor?: string | null;
    cornersDotType?: ('dot' | 'square') | null;
    cornersDotColor?: string | null;
    show?: boolean | null;
    size?: number | null;
    qrSize?: number | null;
    qrX?: number | null;
    qrY?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "new-guest-message".
 */
export interface NewGuestMessage {
  id: string;
  lastTimeRead?: string | null;
  owner?: (string | null) | Guest;
  lastMessage?: (string | null) | GuestMessage;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personalization_select".
 */
export interface PersonalizationSelect<T extends boolean = true> {
  weddingDate?: T;
  couple?:
    | T
    | {
        groom?: T;
        bride?: T;
      };
  headerCopy?: T;
  greetings?: T;
  giftType?: T;
  dressCode?:
    | T
    | {
        text?: T;
        femaleImage?: T;
        maleImage?: T;
      };
  ceremony?:
    | T
    | {
        time?: T;
        placeName?: T;
        gpsCoordinates?:
          | T
          | {
              latitude?: T;
              longitude?: T;
            };
        placePhoto?: T;
        mapPhoto?: T;
      };
  reception?:
    | T
    | {
        time?: T;
        placeName?: T;
        gpsCoordinates?:
          | T
          | {
              latitude?: T;
              longitude?: T;
            };
        placePhoto?: T;
        mapPhoto?: T;
      };
  carousel?:
    | T
    | {
        image?: T;
        id?: T;
      };
  qrLayout?:
    | T
    | {
        backgroundImage?: T;
        dotsType?: T;
        color?: T;
        cornersSquareType?: T;
        cornersSquareColor?: T;
        cornersDotType?: T;
        cornersDotColor?: T;
        show?: T;
        size?: T;
        qrSize?: T;
        qrX?: T;
        qrY?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "new-guest-message_select".
 */
export interface NewGuestMessageSelect<T extends boolean = true> {
  lastTimeRead?: T;
  owner?: T;
  lastMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}